### PR TITLE
More robust variant of roc_auc_score.

### LINKED ISSUE #4: ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
Hi,
steps to repro:

- setup conda env based on the yaml;
- downloaded dataset from Kaggle for pneumonia, copied under input/chest-xray-pneumonia
- downloaded dataset from Covid chestray, copied under input/covid_chestray

From input folder:
```
.
./.gitkeep
./chest-xray-pneumonia
./chest-xray-pneumonia/train
./chest-xray-pneumonia/chest_xray
./chest-xray-pneumonia/__MACOSX
./chest-xray-pneumonia/test
./chest-xray-pneumonia/val
./covid_chestxray
./covid_chestxray/README.md
./covid_chestxray/images
./covid_chestxray/docs
./covid_chestxray/metadata.csv
./covid_chestxray/.git
./covid_chestxray/CONTRIBUTING.md
./covid_chestxray/.~lock.metadata.csv#
./covid_chestxray/.gitignore
```

- run train.py script from conda env, with current default params.

```
`Python version: 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
NumPy version: 1.18.1
scikit-learn version: 0.22.1
pandas version: 1.0.3
OpenCV version: 4.2.0
Torch version: 1.4.0
Available GPUs: 1
Torch device: cuda
ChestXRayPneumoniaDataset initialized with size=256, augment=None
Dataset is located in input/chest-xray-pneumonia
Dataset:                                                   image label
0     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
1     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
2     input/chest-xray-pneumonia/train/NORMAL/NORMAL...     0
3     input/chest-xray-pneumonia/train/NORMAL/IM-051...     0
4     input/chest-xray-pneumonia/train/NORMAL/IM-035...     0
...                                                 ...   ...
5851  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5852  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5853  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5854  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1
5855  input/chest-xray-pneumonia/test/PNEUMONIA/pers...     1

[5856 rows x 2 columns]
Trainer started with classifier: Resnet34 dataset: <datasets.chest_xray_pneumonia_dataset.ChestXRayPneumoniaDataset object at 0x7f28dd548e90> batch size: 64
Train set: 4684
Validation set: 1172
Training with 74 mini-batches per epoch
Logging performance every 15 iter, smoothing every: 74 iter
SGD (
Parameter Group 0
    dampening: 0
    initial_lr: 0.01
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0.0001
)'
<torch.optim.lr_scheduler.StepLR object at 0x7f285c7c2450>'
BCELoss()'
[Accuracy(), <function roc_auc_score at 0x7f285c1af560>]'
                    |         VALID        |        TRAIN         |         
 lr     iter  epoch | loss    roc    acc   | loss    roc    acc   |  time   
------------------------------------------------------------------------------
0.010000    0   0.0 |                      | 0.911  0.269  0.391  |   1.66
0.010000   15   0.2 |                      | 0.370  0.961  0.828  |  13.05
0.010000   30   0.4 |                      | 0.144  1.000  0.938  |  24.79
0.010000   45   0.6 |                      | 0.160  0.984  0.953  |  37.48
0.010000   60   0.8 |                      | 0.085  1.000  0.984  |  49.68
0.010000   74   1.0 | 0.123* 1.000  0.950  | 0.278* 0.935  0.882  |  75.19
0.010000   75   1.0 |                      | 0.081  0.986  0.984  |  77.23
0.010000   90   1.2 |                      | 0.105  0.997  0.984  |  88.95
0.010000  105   1.4 |                      | 0.097  0.989  0.953  | 100.94
0.010000  120   1.6 |                      | 0.087  0.993  0.984  | 112.91
0.010000  135   1.8 |                      | 0.025  1.000  1.000  | 124.32
0.010000  148   2.0 | 0.079* 1.000  0.950  | 0.091* 0.995  0.975  | 148.05
COVIDChestXRayDataset initialized with size=256, augment=None
Dataset is located in input/covid_chestxray
Dataset:                                                  image  label
0    input/covid_chestxray/images/auntminnie-a-2020...   True
1    input/covid_chestxray/images/auntminnie-b-2020...   True
2    input/covid_chestxray/images/auntminnie-c-2020...   True
3    input/covid_chestxray/images/auntminnie-d-2020...   True
4    input/covid_chestxray/images/nejmc2001573_f1a....   True
..                                                 ...    ...
159  input/covid_chestxray/images/pneumocystis-jiro...  False
160  input/covid_chestxray/images/pneumocystis-jiro...  False
161  input/covid_chestxray/images/pneumocystis-jiro...  False
162  input/covid_chestxray/images/legionella-pneumo...  False
163  input/covid_chestxray/images/legionella-pneumo...  False

[164 rows x 2 columns]
Executing a 5-fold cross validation
===Split #1===
Trainer started with classifier: Resnet34 dataset: <datasets.covid_chestxray_dataset.COVIDChestXRayDataset object at 0x7f28cca6e490> batch size: 64
Train set: 131
Validation set: 33
Training with 3 mini-batches per epoch
Logging performance every 1 iter, smoothing every: 3 iter
SGD (
Parameter Group 0
    dampening: 0
    initial_lr: 0.01
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0.0001
)'
<torch.optim.lr_scheduler.StepLR object at 0x7f285c124b50>'
BCELoss()'
[Accuracy(), <function roc_auc_score at 0x7f285c1af560>]'
                    |         VALID        |        TRAIN         |         
 lr     iter  epoch | loss    roc    acc   | loss    roc    acc   |  time   
------------------------------------------------------------------------------
0.010000    0   0.3 |                      | 2.232  0.357  0.516  |   3.19
0.010000    1   0.7 |                      | 2.492  0.448  0.500  |   7.16
0.010000    2   1.0 |                      | 4.214  0.000  0.333  |   7.20
0.010000    3   1.0 | 1.190* 0.474  0.606  | 2.980* 0.268  0.450  |   8.29
0.010000    3   1.3 |                      | 1.330  0.586  0.609  |  11.71
0.010000    4   1.7 |                      | 1.933  0.442  0.578  |  15.22
Traceback (most recent call last):
  File "/home/alessandro/workspace/defeatcovid19-net-pytorch/train.py", line 34, in <module>
    trainer.run(max_epochs=15)
  File "/home/alessandro/workspace/defeatcovid19-net-pytorch/trainer/trainer.py", line 106, in run
    batch_acc, batch_roc = [i(labels.cpu(), preds.cpu()).item() for i in metrics]
  File "/home/alessandro/workspace/defeatcovid19-net-pytorch/trainer/trainer.py", line 106, in <listcomp>
    batch_acc, batch_roc = [i(labels.cpu(), preds.cpu()).item() for i in metrics]
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 390, in roc_auc_score
    sample_weight=sample_weight)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_base.py", line 77, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 221, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.`
```

Similar issue also with dockerbuild (see pull request). Maybe is something related at current params on the script? Or maybe that cuda runtime on my driver is 10.2

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro RTX 5000...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   40C    P8    13W /  N/A |    878MiB / 16125MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
```

### PR DESCRIPTION
**Pull request by mrtj**
I propose this workaround: if there is only one target label in the batch, fall back to accuracy score instead of ROC/AUC. Idea taken from https://stackoverflow.com/a/55349160/1242446

### CODE REVIEW

**Comment by thundo** [comment]
As the error notes, if a class is not present in the truth of a batch, 
> ROC AUC score is not defined in that case.

I'm against either throwing an exception (about what? This is the expected behaviour) or returning another metric (e.g. accuracy). The metric is not broken per se.

I don't feel like solving a data imbalance "issue" with a metric "fix". It would probably be better to use another sampling, if possibile, or just join multiple batches that satisfy the class population requirement.

What do you say?

**Comment by mrtj** [comment]
The real problem with this metric is that it makes the success of the training non deterministic. If the data points are sampled randomly to the batches, there will be always a _p > 0_ probability that there are data points of only one class in the batch and in this case the current implementation will simply fail training the model. 

You can mitigate this to some extent dividing the data points in batches in a stratified way, but in the extreme case when you have less data points with a certain label than the number of batches, it will still fail.

Anyhow, I feel that the training should not fail in any case because of the calculation of an "informal" metrics so I would prefer a way not to use this metrics or to make it more robust.

**Comment by thundo** [comment]
Any update on this? Like maybe adding a per-epoch metric evaluation as we discussed?

It could probably be a more robust solution than #9

**Comment by mrtj** [comment]
If you don't distribute the target classes evenly across epochs (which is not always possible if you have particularly few cases of a class), the risk of not having a class in an epoch still remains. Worsened by the last, optionally smaller epoch as pointed out by @alessandroferrari in issue https://github.com/defeatcovid19/defeatcovid19-net-pytorch/issues/4#issuecomment-609432366

**Comment by thundo** [comment]
I don't understand... during an epoch you should training with all your training samples. If you don't have a particular class in your training dataset, we are not doing "regular" classification and that's besides the point.

Aren't you mixing up epochs and batches maybe?

**Comment by alessandroferrari** [comment]
Depending on when you donwloaded covid dataset images, you may have a different number of images included. For example, when I downloaded it, I had 131 images in the training set. Given a minibatch of 64, it means that the first two minibatches are full 64 images, while the last is minibatch in the iteration, includes only 3 samples, that statistically shows up frequently to be of a single class, generating the exception on the ROC metric. Additionally, a gradient based on such a small minibatch can be very noisy, so I believe it is not only a metric problem. Both the solution should work, as long as very small batches do not undermine optimization!

**Comment by mrtj** [comment]
I'm going to open another PR for the end-of-epoch fix.

**Pull request closed without merging**
